#!/bin/bash
DATE=`date -Iminutes`

mkdir /home/we/dust/audio/tape/$DATE
mv /home/we/dust/audio/tape/*.wav /home/we/dust/data/util_scripts/tape$DATE/
/usr/bin/rclone copy /home/we/dust/data/util_scripts/tape$DATE drive:tape/$DATE -P --stats 2s --exclude="node_modules/**" --exclude=".git**"
