#!/bin/bash
DATE=`date -Iminutes`

[ ! -d "/home/we/dust/data/shell_runner" ] && mkdir /home/we/dust/data/shell_runner

mkdir /home/we/dust/audio/tape/$DATE
mkdir /home/we/dust/data/shell_runner/tape$DATE
mv /home/we/dust/audio/tape/*.wav /home/we/dust/data/shell_runner/tape$DATE
#/usr/bin/rclone copy /home/we/dust/data/shell_runner/tape$DATE drive:tape/$DATE -P --stats 2s --exclude="node_modules/**" --exclude=".git**"
