#!/bin/bash
DATE=`date -Iminutes`
NEWDIR=/home/we/dust/data/norns_scripts/op-z$DATE

[ ! -d "/home/we/dust/data/norns_scripts" ] && mkdir /home/we/dust/data/norns_scripts

mkdir $NEWDIR
cp -r /media/usb/* $NEWDIR
#/usr/bin/rclone copy $NEWDIR drive:op-z/$DATE -P --stats 2s --exclude="node_modules/**" --exclude=".git**"
