#!/bin/bash
DATE=`date -Iminutes`
NEWDIR=/home/we/dust/data/util_scripts/op-z$DATE

mkdir $NEWDIR
cp -r /media/usb0/* $NEWDIR
/usr/bin/rclone copy $NEWDIR drive:op-z/$DATE -P --stats 2s --exclude="node_modules/**" --exclude=".git**"
